swagger: '2.0'
info:
  description: API responsible for managing widgets used by customers on a board
  version: 1.0.0
  title: Widgets Management API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost:8080
basePath: /widgets-management-api/v1
tags:
  - name: Widget
    description: Operations regarding widgets management
schemes:
  - http
paths:
  /widgets:
    post:
      tags:
        - Widget
      summary: Creates a new Widget
      operationId: createWidget
      consumes:
        - "application/json"
      parameters:
        - in: body
          name: widget
          description: "Widget that is being saved"
          required: true
          schema:
            $ref: '#/definitions/WidgetCreateRequest'
      responses:
        '200':
          description: Widget suscessfully saved
          schema:
            $ref: "#/definitions/WidgetResponse"
        '500':
          description: Internal error ocurred while saving Widget data
        '400':
          description: Invalid Widget Request Provided

    get:
      tags:
        - Widget
      summary: Gets data of all stored Widgets
      operationId: getWidgets
      produces:
        - "application/json"
      parameters:
        - name: currentPage
          in: "query"
          description: "Current Page"
          required: false
          type: "integer"
          format: "int64"
          minimum: 0
          default: 0
        - name: pageSize
          in: "query"
          description: "Page Size"
          required: false
          type: "integer"
          format: "int64"
          minimum: 1
          maximum: 500
          default: 10
      responses:
        '200':
          description: "Widget list data suscessfully retrieved"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/WidgetResponse"
        '500':
          description: "Internal error ocurred while getting list of Widgets"
        '400':
          description: "Invalid Request"
        '404':
          description: "No Widgets found"

  /widgets/{id}:
    get:
      tags:
        - Widget
      summary: "Find Widget data by ID"
      description: "Returns a single Widget"
      operationId: getWidgetById
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of Widget to be searched"
          required: true
          type: "integer"
          format: "int64"
          minimum: 0
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/WidgetResponse"
        400:
          description: "Invalid Widget ID"
        404:
          description: "Widget not found"

    delete:
      tags:
        - Widget
      summary: Deletes an Widget by ID
      operationId: deleteWidgetById
      parameters:
        - name: "id"
          in: "path"
          description: "ID of Widget to be deleted"
          required: true
          type: "integer"
          format: "int64"
          minimum: 0
      responses:
        '204':
          description: Widget sucessfully deleted
        '500':
          description: Internal error ocurred while deleting Widget
        '400':
          description: Invalid Request Provided
        '404':
          description: Widget doesn't exists

    put:
      tags:
        - Widget
      summary: Updates Widget data
      operationId: updateWidget
      consumes:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of Widget to be updated"
          required: true
          type: "integer"
          format: "int64"
          minimum: 0
        - in: body
          name: widget
          description: "Updated Widget data"
          required: true
          schema:
            $ref: '#/definitions/WidgetUpdateRequest'
      responses:
        '200':
          description: Widget data suscessfully updated
          schema:
            $ref: "#/definitions/WidgetResponse"
        '500':
          description: Internal error ocurred while updating Widget data
        '400':
          description: Invalid Widget Request Provided
        '404':
          description: Widget doesn't exists

definitions:
  WidgetCreateRequest:
    type: object
    required:
      - widget_x
      - widget_y
      - width
      - height
    properties:
      widget_x:
        type: integer
        format: int64
        description: Widget's X Coordinate
      widget_y:
        type: integer
        format: int64
        description: Widget's Y Coordinate
      widget_z_index:
        type: integer
        format: int64
        description: Widget's Z-index
      width:
        type: integer
        format: int64
        minimum: 0
        description: Widget's Width
      height:
        type: integer
        format: int64
        minimum: 0
        description: Widget's Height

  WidgetUpdateRequest:
    type: object
    properties:
      widget_x:
        type: integer
        format: int64
        description: Widget's X Coordinate
      widget_y:
        type: integer
        format: int64
        description: Widget's Y Coordinate
      widget_z_index:
        type: integer
        format: int64
        description: Widget's Z-index
      width:
        type: integer
        format: int64
        minimum: 0
        description: Widget's Width
      height:
        type: integer
        format: int64
        minimum: 0
        description: Widget's Height

  WidgetResponse:
    type: object
    required:
      - widget_x
      - widget_y
      - widget_z_index
      - width
      - height
      - id
      - last_modification_date
    properties:
      id:
        type: integer
        format: int64
        minimum: 0
        description: Widget's ID
      widget_x:
        type: integer
        format: int64
        description: Widget's X Coordinate
      widget_y:
        type: integer
        format: int64
        description: Widget's Y Coordinate
      widget_z_index:
        type: integer
        format: int64
        description: Widget's Z-index
      width:
        type: integer
        format: int64
        minimum: 0
        description: Widget's Width
      height:
        type: integer
        format: int64
        minimum: 0
        description: Widget's Height
      last_modification_date:
        type: string
        minLength: 1
        example: "03/27/2021 12:00:02"
        description: Widget's Last Modification Date